# Generated by Django 4.0.3 on 2022-04-13 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('well', '0003_well_lat_well_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='field',
            name='country',
        ),
        migrations.RemoveField(
            model_name='well',
            name='easting',
        ),
        migrations.RemoveField(
            model_name='well',
            name='northing',
        ),
        migrations.RemoveField(
            model_name='well',
            name='utmzone',
        ),
        migrations.AddField(
            model_name='field',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='well',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='well',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
