# Generated by Django 4.0.3 on 2022-04-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_test_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
