# Generated by Django 4.0.3 on 2022-06-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_test_neutral_error_test_sum_anion_test_sum_cation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stifftemplatelevel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevel',
            name='stiff_template',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevelion',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevelion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevelion',
            name='stiff_template_level',
        ),
        migrations.RemoveField(
            model_name='stifftemplatelevelion',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='StiffTemplate',
        ),
        migrations.DeleteModel(
            name='StiffTemplateLevel',
        ),
        migrations.DeleteModel(
            name='StiffTemplateLevelIon',
        ),
    ]
