# Generated by Django 4.0.3 on 2022-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_remove_stifftemplatelevel_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
