# Generated by Django 4.0.5 on 2022-06-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_samplepoint_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='neutral_error',
            new_name='charge_imbalance_error',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sum_anion',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sum_cation',
        ),
    ]
