# Generated by Django 4.0.5 on 2022-06-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_rename_neutral_error_test_charge_imbalance_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='charge_imbalance_error',
            new_name='charge_balance_error',
        ),
    ]
